version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory_service
    ports:
      - "3317:3306"
    volumes:
      - inventory-mysql-data:/var/lib/mysql
volumes:
  inventory-mysql-data:

